### ISSUE TITLE
Change Google search result links to the correct wiki

### ISSUE THREAD

**Issue by jayktaylor** [proEndreeper/RSWikiRedirector#1]
The redirector is super helpful. I've been thinking about our search ranking though and I think that the extra click from Google still helps Wikia in some shape or form, so if possible, implementing a feature to actually change links on Google search results to the right wiki before they're even clicked on would be pretty damn good.

**Comment by speeditor** [comment]
In Google search results, you need to strip or replace the ping attribute from those old wiki links. That's the tracking utility that Google uses, before the client lands on the old wiki. Then you need to override the href attribute.
Replacing the ping attributes to doubly benefit the new wiki would require an XHR to a different Google search page (which isn't efficient at all).

**Comment by dovry** [comment]
[Here](https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites) is something to get you started. Allows for blocking (collapses webpage) or permabanning (hides results completely)

Here is without script
![image](https://user-images.githubusercontent.com/15201298/50763964-a1670b00-1271-11e9-836d-06cc6ca28a1e.png)

Here is with script enabled and "runescape.fandom.com" pernabanned
![image](https://user-images.githubusercontent.com/15201298/50764069-eab75a80-1271-11e9-839e-1a88ad040919.png)

**Comment by RMHonor** [comment]
@Dovry I think your solution is better than redirecting. I'm not sure on how Google registers clicks, but I would imagine even with the URL rewriting, this still has a positive page rank result for wikia URLs

**Comment by proEndreeper** [comment]
Implemented so that it removes search results going to Wikia/Fandom on Google with RMHonor's code, adjusted so it shows a message stating the search result was removed.

**Comment by proEndreeper** [comment]
Closing this issue since a solution was implemented.
